// automatically generated interface
#define HSHADER_COUNT 23

#define HSHADER_GBOOK 0
#define HSHADER_OTHOGRAPHIC 1
#define HSHADER_STATIC_DEFAULT 2
#define HSHADER_MSAA 3
#define HSHADER_STATIC_DEFAULT_100 4
#define HSHADER_SCIFI 5
#define HSHADER_FABRICGALLERY 6
#define HSHADER_PPL 7
#define HSHADER_CAMERA 8
#define HSHADER_STATIC_PPL_100 9
#define HSHADER_CUBEMAP 10
#define HSHADER_SHADOW_CAST 11
#define HSHADER_DEFAULT 12
#define HSHADER_RIPPLE 13
#define HSHADER_SIMPLE 14
#define HSHADER_GLOWING_TEXTURE 15
#define HSHADER_CAMERA_OCULUS_RIFT 16
#define HSHADER_FIRE 17
#define HSHADER_RUBIK 18
#define HSHADER_CURLY 19
#define HSHADER_STATIC_PPL 20
#define HSHADER_BUMP 21
#define HSHADER_WAVVY 22
