// automatically generated interface
#define HSHADER_COUNT 23

#define HSHADER_BUMP 0
#define HSHADER_CAMERA 1
#define HSHADER_CAMERA_OCULUS_RIFT 2
#define HSHADER_CUBEMAP 3
#define HSHADER_CURLY 4
#define HSHADER_DEFAULT 5
#define HSHADER_FABRICGALLERY 6
#define HSHADER_FIRE 7
#define HSHADER_GBOOK 8
#define HSHADER_GLOWING_TEXTURE 9
#define HSHADER_MSAA 10
#define HSHADER_OTHOGRAPHIC 11
#define HSHADER_PPL 12
#define HSHADER_RIPPLE 13
#define HSHADER_RUBIK 14
#define HSHADER_SCIFI 15
#define HSHADER_SHADOW_CAST 16
#define HSHADER_SIMPLE 17
#define HSHADER_STATIC_DEFAULT 18
#define HSHADER_STATIC_DEFAULT_100 19
#define HSHADER_STATIC_PPL 20
#define HSHADER_STATIC_PPL_100 21
#define HSHADER_WAVVY 22
